### ISSUE TITLE
use seeded RNG to generate hands

### ISSUE THREAD

**Issue by randName** [yf-dev/mahjong-hand-guessing-game#13]
thanks for making such a great variant!

instead of having a large array of hands, just use a seeded RNG? maybe something like https://github.com/cprosche/mulberry32 seeded with the day with a hash, e.g.
```js
const epochMs = new Date('February 2, 2022 00:00:00').valueOf()
const now = Date.now()
const msInDay = 86400000
const index = Math.floor((now - epochMs) / msInDay)

const data = new Uint32Array([index])
const hash = await crypto.subtle.digest('SHA-256', data.buffer)
const digest = new Uint32Array(hash)

let seed = digest[0]
const int32 = 2 ** 32
// mulberry32. use in generateHands.ts
const random = () => {
  let t = seed += 0x6D2B79F5
  t = Math.imul(t ^ t >>> 15, t | 1)
  t ^= t + Math.imul(t ^ t >>> 7, t | 61)
  return ((t ^ t >>> 14) >>> 0) / int32
}
```

might be hard to check if there is a problem with hands (like #8) but should be ok to generate hands for the next 10 years (lol) to check if there are any issues

**Comment by rishubil** [comment]
We're offering about 10,000 hands now, so there's no problem for about 27 years!

But I don't know if I'll work as you suggested one day :smile:
