### ISSUE TITLE
Site blocked by Quad9 DNS

### ISSUE THREAD

**Issue by mikitakahazekura** [yf-dev/mahjong-hand-guessing-game#24]
The website is blocked by Quad9 DNS Provider. I wrote an e-mail saying it was a false positive, but sadly the website is still blocked.
![jqLkdoa](https://user-images.githubusercontent.com/24222032/166122099-d648b2e2-f91b-4e55-9ee5-220879f4d8dc.png)

**Comment by rishubil** [comment]
Well, I also asked for confirmation that it was false positive, but there is nothing else I can do right now.
I think we have no choice but to wait until we get an answer.

**Comment by rishubil** [comment]
![image](https://user-images.githubusercontent.com/382014/166234847-fe6eb666-ce65-4683-9c26-39a7ec944462.png)
