### ISSUE TITLE
Add practice or infinite mode

### ISSUE THREAD

**Issue by BlindJack** [yf-dev/mahjong-hand-guessing-game#5]
as title,
how about add an practice or infinite mode?
like a wordle branch 
https://codepen.io/jfledd/full/ExwGqrz

**Comment by rishubil** [comment]
Thank you for your suggestion.
I think the most important thing in a game like Wordle is that "only once a day, everyone has the same answer".
So there is no plan to apply the practice or infinite mode to the game.
