### ISSUE TITLE
역 이름 표시

### ISSUE THREAD

**Issue by rishubil** [yf-dev/mahjong-hand-guessing-game#6]

**Comment by rishubil** [comment]
역 이름을 직접 표시하는 것 대신 점수를 표시하는 쪽으로 고려중

**Comment by lens0021** [comment]
정답을 맞힌 다음에 역 이름이 나오는 것도 좋을 것 같습니다.

**Comment by rishubil** [comment]
이 이슈는 한국어로 작성되어, 다른 국가 사람들이 확인하기 어려우므로, 추후 논의는 #20 에서 이어서 진행합니다.
