### ISSUE TITLE
정답 핸드 목록에서 같은 패가 5장 있는 화료패가 있음

### ISSUE THREAD

**Issue by DailyPS** [yf-dev/mahjong-hand-guessing-game#8]
hands.ts 에서
1m, 1p, 1s, 1~7z 를 제외하고
각 경우마다 5장 쓰이는 화료패 형태가 있습니다.

확인이 필요할 것 같습니다.

**Comment by rishubil** [comment]
확인했습니다. 확실히 문제가 있네요.
