### ISSUE TITLE
A single tap will enter two tiles.

### ISSUE THREAD

**Issue by neko-kawaii-nyan** [yf-dev/mahjong-hand-guessing-game#9]
# Reproduction environment
## smartphone
Occurs in safari on mac
Dont occur in chrome98.0.4758.87 on Android11

## PC
Don't occur in PC environment.

**Comment by crowrish** [comment]
I'm guessing it might be related to this link.
https://stackoverflow.com/questions/22922267/touch-events-double-firing-on-safari-for-ios

```ts
  const handleClick: React.MouseEventHandler<HTMLButtonElement> = (event) => {
    event.preventDefault(); // <-- new
    onClick(value)
    event.currentTarget.blur()
  }
```

Since I don't have the environment in place, this case needs testing.

**Comment by rishubil** [comment]
I don't have an iPhone either, so I can't test it.
I think we need someone else's help 😢

**Comment by rishubil** [comment]
We can't check if it has been resolved, but I'll close the issue now.
If the same problem still occurs, please open a new issue.
